FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    ca-certificates \
    xz-utils \
    tar \
    gzip \
    file \
    make \
    gcc \
    libncurses-dev \
    zsh \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash tester

USER tester
WORKDIR /home/tester
CMD ["bash"]
